# Generated by Django 6.0.1 on 2026-02-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user_lead_user_works_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='lead',
        ),
        migrations.AlterUniqueTogether(
            name='assignedwork',
            unique_together={('employee', 'work')},
        ),
    ]
